apiVersion: apps/v1
kind: Deployment
metadata:
  name: web00
  labels:
    app: web00
  namespace: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web00
  template:
    metadata:
      labels:
        app: web00
    spec:
      containers:
      - name: web00
        image: 
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: web00
  namespace: react
spec:
  type: NodePort
  selector:
    app: web00
  ports:
    - name: web00-tcp
      port: 3000
      protocol: TCP
      nodePort: 30002