name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup repository
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: run test
        uses: actions/checkout@v3
      - run: echo 'alo runing'

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: 
      - build
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github package
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: maxdarkskies/gitops:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
      - test
      - build-and-push-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Update docker image
        run: |
          cp deploy/template/web00-template.yml deploy/web00.yml
          sed -i 's|image: ${{ IMG }}|image: ${{ REPO }}/${{ IMG_URL }}:${{ github.sha }}|g' deploy/web00.yaml

        